# ===== PROD profile =====
spring.datasource.url=jdbc:h2:mem:gymdb_prod;DB_CLOSE_DELAY=-1
spring.datasource.username=prod_sa
spring.datasource.password=prod_pass456

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=WARN
logging.level.com.epam.springCoreTask=WARN
