spring.application.name=gymCRM

# Active profile (override via -Dspring.profiles.active=dev|stg|prod)
spring.profiles.active=local

# Common JPA settings
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging Configuration
logging.level.root=INFO
logging.level.com.epam.springCoreTask=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %X{transactionId} - [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %X{transactionId} - [%thread] %-5level %logger{36} - %msg%n

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

spring.web.resources.add-mappings=false

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.metrics.export.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoint.prometheus.enabled=true
management.info.env.enabled=true
info.app.name=GymCRM
info.app.description=Gym CRM Spring Boot Application